### ISSUE TITLE
Problem with slots with differents signatures

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/pydm-pyqt5#3]
Problem on PyQt5.6 and higher

**Comment by laispc** [comment]
Possible solution added in branch iss3. Solved this issue for PyQt 5.6, but needs to be tested for other versions.

**Comment by gabrielfedel** [comment]
Tested with Qt 5.3.2 and Qt 4.8.6

**Comment by laispc** [comment]
Okay, pull request done.

**Comment by gabrielfedel** [comment]
Thank you!
